name: OpenKore Bot Runner

on:
  workflow_dispatch:  # Permite executar manualmente

jobs:
  run-openkore:
    runs-on: windows-latest  # Usa ambiente Windows

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: Instalar dependências Perl
        run: |
          cpanm IO::Socket::SSL
          cpanm Encoding::FixLatin

      - name: Baixar config.txt
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Rilufi/openkore/master/control/config.txt" -OutFile "control/config.txt"

      - name: Substituir credenciais no config.txt
        run: |
          (Get-Content "control/config.txt") |
          ForEach-Object {
            $_ -replace '\$ENV\{''RO_USERNAME''\}', "$env:RO_USERNAME" `
               -replace '\$ENV\{''RO_PASSWORD''\}', "$env:RO_PASSWORD" `
               -replace '\$ENV\{''RO_PIN''\}', "$env:RO_PIN"
          } | Set-Content "control/config.txt"
        env:
          RO_USERNAME: ${{ secrets.RO_USERNAME }}
          RO_PASSWORD: ${{ secrets.RO_PASSWORD }}
          RO_PIN: ${{ secrets.RO_PIN }}

      - name: Rodar o OpenKore via Perl
        run: perl openkore.pl
        working-directory: ./  # Diretório onde está o openkore.pl
        timeout-minutes: 30

