name: OpenKore Bot Runner

on:
  workflow_dispatch:

jobs:
  run-openkore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y perl cpanminus libio-socket-ssl-perl libencoding-fixlatin-perl \
            libreadline-dev libncurses-dev libcurl4-openssl-dev make gcc python3

      - name: Instalar módulos Perl necessários
        run: |
          cpanm IO::Socket::SSL
          cpanm Encoding::FixLatin

      - name: Substituir variáveis no config.txt
        run: |
          sed -i "s/\$ENV{RO_USERNAME}/${RO_USERNAME}/g" control/config.txt
          sed -i "s/\$ENV{RO_PASSWORD}/${RO_PASSWORD}/g" control/config.txt
          sed -i "s/\$ENV{RO_PIN}/${RO_PIN}/g" control/config.txt
        env:
          RO_USERNAME: ${{ secrets.RO_USERNAME }}
          RO_PASSWORD: ${{ secrets.RO_PASSWORD }}
          RO_PIN: ${{ secrets.RO_PIN }}

      - name: Compilar XSTools com scons
        run: python3 src/scons-local-*/scons.py

      - name: Executar OpenKore
        run: perl openkore.pl
        working-directory: ./
        timeout-minutes: 30
